observer:
  sinks:
    MyMongoSink:
      type: MongoSink
      config:
        uri: "mongodb://root:password@docker_demo_5_mongo:27017"
        database: "ortc_reports"
    MyKafkaSink:
      type: KafkaSink
      config:
        muxReports: true
        muxTopic: "ortc_demo_5_reports"

        # If muxReports property is false, then each type of report is 
        # sent to a separated topic, and the preix can be set through the following 
        # property
        demuxTopicPrefix: "ortc_demo_5_"

        # Kafka Producer Configurations. see: https://kafka.apache.org/documentation/#producerconfigs
        properties:
          bootstrap.servers: "docker_demo_5_kafka:29092"


