version: '3.3'
services:
  observer:
    restart: always
    container_name: docker_observertc_observer
    image: observertc/observer:0.6.1
    ports:
      - 7080:7080
      - 7081:7081
    environment:
      - INITIAL_WAITING_TIME_IN_S=5
#      - MICRONAUT_CONFIG_FILES=/observer-config.yaml
      - HAZELCAST_CONFIG_FILE=/hazelcast-config.yaml
    volumes:
#      - ./quick-observer-config.yaml:/observer-config.yaml
      - ./hazelcast-config.yaml:/hazelcast-config.yaml