services:
  observer:
    restart: always
    image: observertc/observer:1.0.0-beta
    ports:
    - 7080:7080
    environment:
    - MICRONAUT_CONFIG_FILES=/my-config.yaml
    volumes:
    - ./observer-config/config.yaml:/my-config.yaml
  mongodb:
    image: mongo:4.2
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - 27017:27017
    restart: always
  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    restart: always
    depends_on:
    - mongodb
  sfu:
    build:
      context: ./mediasoup-sfu
      dockerfile: Dockerfile
    network_mode: bridge
    ports:
    - 15000-15900:15000-15900/udp
    - 5959:5959
    environment:
    - HOSTNAME=localhost
    - RTCMIN_PORT=15000
    - RTCMAX_PORT=15900
    - WEBPAGE_PORT=5959
    - SERVER_IP=0.0.0.0
    - ANNOUNCED_IP=${SFU_ANNOUNCED_IP}
    - OBSERVER_INTERNAL_ADDRESS=host.docker.internal:7080
    depends_on:
    - observer
  webrtc-app:
    build:
      context: ./my-webrtc-app
      dockerfile: Dockerfile
    ports:
    - 9000:9000
    depends_on:
    - observer
version: '3.3'