observer:
  servicemappings:
    - name: "example-service-name"
      uuids:
        - "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
  connectors:
    - name: "MyKafkaReportSink"
      buffer:
        maxItems: 100
        maxWaitingTimeInS: 10
      sink:
        type: KafkaSink
        config:
          topic: "reports"
          properties:
            bootstrap.servers: ${KAFKA_HOSTS}
  evaluators:
    observedPCSBufferMaxTimeInS: 10
    observedPCSBufferMaxItemNums: 10000
    peerConnectionMaxIdleTimeInS: 60
  outboundReports:
    reportOutboundRTPs: True
    reportInboundRTPs: True
    reportRemoteInboundRTPs: True
    reportTracks: True
    reportMediaSources: True
    reportCandidatePairs: True
    reportLocalCandidates: True
    reportRemoteCandidates: True
    reportUserMediaErrors: True


