observer:
  connectors:
    - name: "QuickStartConnector"
      buffer:
        maxItems: 100
        maxWaitingTimeInS: 10
      sink:
        type: LoggerSink
        config:
          printReports: True


