services:
  observer:
    restart: always
    image: observertc/observer:1.0.0-beta
    ports:
    - 7080:7080
    environment:
    - INITIAL_WAITING_TIME_IN_S=30
    - MICRONAUT_CONFIG_FILES=/observer-config.yaml
    volumes:
    - ./observer-config/config.yaml:/observer-config.yaml
  mongodb:
    image: mongo:4.2
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - 27017:27017
    restart: always
  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    restart: always
    depends_on:
    - mongodb
version: '3.3'
