observer:
  sinks:
    MyKafkaSink:
      type: KafkaSink
      config:
        muxReports: true
        muxTopic: "ortc_reports"

        # If muxReports property is false, then each type of report is 
        # sent to a separated topic, and the preix can be set through the following 
        # property
        demuxTopicPrefix: "ortc_"

        # Kafka Producer Configurations. see: https://kafka.apache.org/documentation/#producerconfigs
        properties:
          bootstrap.servers: "docker_kafka:29092"


