version: '3.3'
services:
  observer:
    extends:
      file: ../common-services.yaml
      service: observer
    environment:
      - MICRONAUT_CONFIG_FILES=/observer-config.yaml
    restart: always
    depends_on:
      - kafka
    volumes:
      - ./observer-config/config.yaml:/observer-config.yaml
  zookeeper:
    extends:
      file: ../common-services.yaml
      service: zookeeper
    restart: always
  kafka:
    extends:
      file: ../common-services.yaml
      service: kafka
    depends_on: 
      - zookeeper
    restart: always
  kafka-setup:
    extends:
      file: ../common-services.yaml
      service: kafka-setup
    depends_on: 
      - kafka
  nodered:
    image: observertc/node-red:latest
    ports:
      - 1880:1880
    volumes:
      - ./node_red_data:/data
