version: '3.3'
services:
  observer:
    restart: always
    container_name: docker_observertc_observer
    image: observertc/observer:1.0.0-alpha
    ports:
      - 7080:7080
    volumes:
      - ./quick-fullstack-observer-config.yaml:/fullstack-observer-config.yaml
      - ./hazelcast-config.yaml:/hazelcast-config.yaml
