version: '3.3'
services:
  observer:
    extends:
      file: ../common-services.yaml
      service: observer
    environment:
      - MICRONAUT_CONFIG_FILES=/observer-config.yaml
      - INITIAL_WAITING_TIME_IN_S=1
    restart: always
    volumes:
      - ./observer-config/config.yaml:/observer-config.yaml
    links:
    - myapp
  myapp:
    build: # "context" and "dockerfile" fields have to be under "build"
      context: ./myApp
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5080:5080