services:
  observer:
    restart: always
    image: observertc/observer:1.0.0-beta
    ports:
    - 7080:7080
    environment:
    - INITIAL_WAITING_TIME_IN_S=30
    - MICRONAUT_CONFIG_FILES=/observer-config.yaml
    - INITIAL_WAITING_TIME_IN_S=1
    volumes:
    - ./observer-config/config.yaml:/observer-config.yaml
    links:
    - myapp
  myapp:
    build:
      context: ./myApp
      dockerfile: Dockerfile
    restart: always
    ports:
    - 5080:5080
version: '3.3'
